# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('email', models.EmailField(default=None, max_length=120, unique=True)),
                ('firstname', models.CharField(default=None, max_length=120)),
                ('lastname', models.CharField(default=None, max_length=120)),
                ('password', models.CharField(default=None, max_length=128)),
                ('phone_number', models.CharField(default=None, max_length=10)),
            ],
        ),
    ]
