# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20170930_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNO',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
