# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20170930_0348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastName',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phoneNO',
            new_name='phone_number',
        ),
    ]
