# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CatagoryMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.Catagory')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.DecimalField(decimal_places=0, max_digits=13, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('publisher', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('weight', models.FloatField()),
                ('isMonocrome', models.BooleanField(default=True)),
                ('paperType', models.CharField(max_length=100)),
                ('coverType', models.CharField(max_length=100)),
                ('size_height', models.FloatField()),
                ('size_width', models.FloatField()),
                ('size_thickness', models.FloatField()),
                ('description', models.TextField()),
                ('pictureUrl', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.Product', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='catagorymap',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.Product'),
        ),
    ]
