# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0004_auto_20170927_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='coverType',
            field=models.CharField(choices=[('PD', 'Paperback'), ('HC', 'Hardcover')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='paperType',
            field=models.CharField(choices=[('NS', 'Newsprint'), ('CP', 'Coated Paper'), ('UP', 'Uncoated Paper'), ('BP', 'Bond Paper'), ('GR', 'Green Read Paper')], max_length=2),
        ),
    ]
